language: go
go:
  - "1.11"
  - "1.12"
  - "1.13"
before_install:
  - go get github.com/4thel00z/gojsonreference
  - go get github.com/4thel00z/gojsonpointer
  - go get github.com/stretchr/testify/assert
